# Generated by Django 4.1 on 2022-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_project_alter_skills_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/image')),
                ('descriptions', models.CharField(max_length=5000)),
            ],
        ),
    ]
