# Generated by Django 4.1 on 2022-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(upload_to='person/static/image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='person/static/image'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='person/static/image'),
        ),
    ]
